//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeodeviburdur.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nufu
    {
        public int Id { get; set; }
        public int Yil { get; set; }
        public int NufusSayisi { get; set; }
    }
}
